name = "CDMSreader"
version = "1.0.0"
license = "GPL2"
author = "banana-bred"
maintainer = "j.forer@posteo.net"
copyright = "Copyright 2025, banana-bred"

[build]
auto-executables = true
auto-examples = true
module-naming = true

[library]
source-dir = "src"

[install]
library = false

[[executable]]
main = "CDMSreader.f"
source-dir = "main"
name = "cdmsreader"

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
